### ISSUE TITLE
Translating file / Clouds altitude / Forecast

### ISSUE THREAD

**Issue by MauroSwiss88** [steepleian/weewx-Weather34#2]
Hi! 

I have three questions:

1) By choosing a translating file (in this case, the Italian one) I noticed that parts of the text remain in English, for example the Beaufort scale. Is there an issue on it?

2) The Clouds altitude in the current conditions box is given in feet and not meter. Where can I changed it? Is there a possibility to change to Italian also the text?

3) How can I translate the forecast conditions text to Italian? (For example: Partly cloudy = parzialmente nuvoloso, etc) 

Thank you for the great job!!

**Comment by steepleian** [comment]
Hi,
All of the translations were contributed by enthusiasts.
You can make translations for yourself very easily by editing *lang.it.php *in
the languages folder*. *Any word can be translated, you just need to create
a variable for it and then substitute that variable for the English word in
the code.
The forecasts come from Dark Sky and Weather Underground. If you go to
lines 107 and 110 in settings1.php, you can change your language setting to
Italian.

I have fixed the cloud base height unit switching. If wind speed settings
of mph or kts are used, feet are displayed, for km/h and m/s, meters are
displayed.

You need to replace the archivedata.php.tmpl file in your skins/Weather34
folder, w34CombinedData.php and currentconditionsw34.php in your weather34
folder
Regards,
Ian

**Comment by MauroSwiss88** [comment]
Hi Ian,
thank you for your answer.
The cloud base height is working perfectly! :)

For the forecast I checked my settings.1.php on my Raspberry (line 107 an 110)
I think they already are set to Italian, but I still get the prediction in English:

> $ds_url = 'https://api.forecast.io/forecast/YOURDARKSKYKEY/42.6344,14.0406?lang=it&units=uk2';
> $ds_interval = '300';
> $ds_filename = '/var/www/html/weewx/weather34/jsondata/darksky.txt';
> $wu_url = 'https://api.weather.com/v3/wx/forecast/daily/5day?geocode=42.6344,14.0406&language=it&format=json&units=h&apiKey=634283b9282648558283b92826a855cf';

For the normale translations I noted that on lang.it.php the wind phrases from Beaufort scales are still translated, but they are shown in English when opening index.php.

lang_it.php file
> // Wind phrases for Beaufort scale for windspeed area
> $lang['Calm']                   = 'Calma';
> $lang['Lightair']               = 'Bava di Vento';
> $lang['Lightbreeze']            = 'Brezza Leggera';
> $lang['Gentelbreeze']           = 'Brezza tesa';
> $lang['Moderatebreeze']         = 'Vento moderato';
> $lang['Freshbreeze']            = 'Vento teso';
> $lang['Strongbreeze']           = 'Vento fresco';
> $lang['Neargale']               = 'Vicino a burrasca';
> $lang['Galeforce']              = 'Gale Burrasca';
> $lang['Stronggale']             = 'Burrasca forte';
> $lang['Storm']                  = 'Tempesta';
> $lang['Violentstorm']           = 'Tempesta violenta';
> $lang['Hurricane']              = 'Uragano';
> // Wind phrases from Beaufort scale for current conditions area
> $lang['CalmConditions']         = 'Condizioni di Calma';
> $lang['LightBreezeattimes']     = 'Bava di Vento ';
> $lang['MildBreezeattimes']      = 'Brezza Leggera ';
> $lang['ModerateBreezeattimes']  = 'Brezza Tesa';
> $lang['FreshBreezeattimes']     = 'Vento Moderato';
> $lang['StrongBreezeattimes']    = 'Vento Teso';
> $lang['NearGaleattimes']        = 'Vento Fresco';
> $lang['GaleForceattimes']       = 'Vento Forte';
> $lang['StrongGaleattimes']      = 'Burrasca';
> $lang['StormConditions']        = 'Tempesta';
> $lang['ViolentStormConditions'] = 'Tempesta Violenta';
> $lang['HurricaneConditions']    = 'Uragano';
> $lang['Avg']                    = '<span2> Avg: </span2>';

windspeedirection.php

>  <weather34bftspan>BFT<weather34bftspan></div>
> <div class="beaufort1"><?php
> if ($weather["wind_speed_bft"] == 0) {
>   echo "Calm";
> } else if ($weather["wind_speed_bft"] == 1) {
>   echo "Light Air";
> } else if ($weather["wind_speed_bft"] == 2) {
>   echo "Light Breeze";
> } else if ($weather["wind_speed_bft"] == 3) {
>   echo "Gentle Breeze";
> } else if ($weather["wind_speed_bft"] == 4) {
>   echo "Moderate Breeze";
> } else if ($weather["wind_speed_bft"] == 5) {
>   echo "Fresh Breeze";
> } else if ($weather["wind_speed_bft"] == 6) {
>   echo "Strong Breeze";
> } else if ($weather["wind_speed_bft"] == 7) {
>   echo "Near Gale " . $alert . "";
> } else if ($weather["wind_speed_bft"] == 8) {
>   echo "Gale Force " . $alert . "";
> } else if ($weather["wind_speed_bft"] == 9) {
>   echo "Strong Gale " . $alert . "";
> } else if ($weather["wind_speed_bft"] == 10) {
>   echo "Storm Force " . $alert . "";
> } else if ($weather["wind_speed_bft"] == 11) {
>   echo "Violent Storm " . $alert . "";
> } else if ($weather["wind_speed_bft"] >= 12) {
>   echo "Hurricane Force " . $alert . "";
> }
> ?>

**Comment by steepleian** [comment]
Hi,

The cloud base unit fix I have provided is a temporary one. A more
permanent one will be added in due course, however I am glad that it works
for you in the meantime. We are working on another update at the moment.
This will include more charts, including multiple charts in one popup
window, new air quality modules for extended database users and Meteoalarm
alerts for European based users. Hopefully the last item will stimulate
users from other regional locations to contribute to more explicit weather
warning alerts. If you go to my own site and click on alerts under the
forecast module you will see an example. Its still work in progress though.

How proficient are you at PHP? You could go through the wind module and
replace the key English word in the Bft scale section with the variable. If
you can make that work we can check with the other languages.

I could not access your Dark Sky json data but your Weather Underground
data is in Italian. I will investigate further.

Regards,
Ian

**Comment by MauroSwiss88** [comment]
I'm not new to PHP, but I'm not expert too :D I can try, but it's very strange that the lang file does not translate. I have the same issue for the months and days of the week. They are translated but still shown in English. 


You could not access Dark Sky because I haven't one.. it is not possibile to have new API Key since they joined Apple.

Thank you for your efforts.

Kindly regards
Mauro

**Comment by steepleian** [comment]
Hi Mauro,

That sounds just about my level of php expertise:D

I was fortunate enough to have a DarkSky key before they became part of
Apple so I have 18months left before access is curtailed for me. However I
have already got an alternative working solution for Meteoalarm (DarkSky
 channels this alert information currently). The new method uses the
Meteoalarm RSS feed and requires no access key, just location information.
I am currently looking at alternatives for the hourly forecasts.

Ciao,
Ian

**Comment by MauroSwiss88** [comment]
If I understood well you still have to integrate the Meteoalarm RSS to the skin, right?

I'm looking now why the skin doesn't translate the weekly days and months too.

Ciao :-)

**Comment by steepleian** [comment]
Hi Mauro,

Yes but if you want to use it now, I can walk you through installing it in
advance of the roll out (no date set for that yet).

Can I email you directly so we do not clutter up this issue log with many
different threads?

Many thanks,
Ian

**Comment by MauroSwiss88** [comment]
Hi Ian,
of course you can mail me directly :-)

Greetings,
Mauro

**Comment by steepleian** [comment]
Ok but I only have your github address, Just send me a mail from your
personal address to mine to preserve your privacy.
